name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if release exists
        id: check_release
        run: |
          TAG_NAME=$(git describe --tags)
          RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $RELEASE_URL)
          if echo "$RESPONSE" | grep -q '"id":'; then
            echo "Release already exists for tag $TAG_NAME."
            echo "release_exists=true" >> $GITHUB_ENV
          else
            echo "release_exists=false" >> $GITHUB_ENV
          fi
      - name: Stop if release exists
        if: env.release_exists == 'true'
        run: |
          echo "Release already exists, skipping workflow."
          exit 0
      - name: Generate changelog
        id: generate_changelog
        if: env.release_exists == 'false'
        uses: orhun/git-cliff-action@v4
        with:
          args: --latest --strip header
      - name: Create GitHub Release
        id: create_release
        if: env.release_exists == 'false'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.generate_changelog.outputs.content }}
