name: Release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Generate release changelog
        # uses: janheinrichmerker/action-github-changelog-generator@v2.4
        # with:
          # token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate changelog
        id: generate_changelog
        uses: orhun/git-cliff-action@v4
        with:
          args: -vv --latest --strip header
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.generate_changelog.outputs.content }}
