name: Generate Release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate Release
        uses: ./.github/actions/gh-release-gen
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
